# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='strip_id',
            new_name='stripe_id',
        ),
    ]
