# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20161018_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeinvoice',
            name='charge',
        ),
        migrations.AlterField(
            model_name='stripecharge',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='created', max_length=100),
        ),
        migrations.AlterField(
            model_name='stripeinvoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='created', max_length=100),
        ),
    ]
