# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20170317_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='book',
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='default_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
