# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-22 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20170319_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='has_valid_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
