# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-22 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0037_auto_20170322_0434'),
        ('payments', '0010_auto_20170322_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Book'),
        ),
    ]
