# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20160120_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='should_surface',
            field=models.BooleanField(default=True),
        ),
    ]
