# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 04:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20160218_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='document',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='document',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
