# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0008_auto_20160229_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('url', 'URL'), ('date', 'Date'), ('twitter', 'Twitter'), ('phone', 'Phone'), ('address', 'Address'), ('text', 'Short Text'), ('big_text', 'Big Text')], max_length=100)),
                ('preferred', models.BooleanField(default=True)),
                ('value', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalField',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('changed', models.DateTimeField(blank=True, editable=False)),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('url', 'URL'), ('date', 'Date'), ('twitter', 'Twitter'), ('phone', 'Phone'), ('address', 'Address'), ('text', 'Short Text'), ('big_text', 'Big Text')], max_length=100)),
                ('preferred', models.BooleanField(default=True)),
                ('value', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.Contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical field',
            },
        ),
    ]
