# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_field_historicalfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='ContactField',
        ),
        migrations.RenameModel(
            old_name='HistoricalField',
            new_name='HistoricalContactField',
        ),
        migrations.AlterModelOptions(
            name='historicalcontactfield',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact field'},
        ),
    ]
