# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20160309_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='document',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='document',
        ),
    ]
