# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20160314_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfield',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcontactfield',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
