# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20160722_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogentry',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallogentry',
            name='external_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallogentry',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallogentry',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='external_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='kind',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('tumblr', 'Tumblr'), ('facebook', 'Facebook'), ('email', 'Email'), ('in person', 'In Person'), ('foursquare', 'Foursquare'), ('website', 'Website'), ('other', 'Other'), ('edit', 'Edit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='kind',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('tumblr', 'Tumblr'), ('facebook', 'Facebook'), ('email', 'Email'), ('in person', 'In Person'), ('foursquare', 'Foursquare'), ('website', 'Website'), ('other', 'Other'), ('edit', 'Edit')], max_length=100, null=True),
        ),
    ]
