# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 23:46
from __future__ import unicode_literals

from django.db import migrations, models


def populate_log_time(apps, schema_editor):
    LogEntry = apps.get_model("contacts", "LogEntry")
    for log in LogEntry.objects.all():
        if not log.time:
            log.time = log.created
            log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20160725_0354'),
    ]

    operations = [
        migrations.RunPython(populate_log_time)
    ]
