# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20161010_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tumblr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_phone',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='tumblr',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='website',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='work_email',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='work_phone',
        ),
    ]
