# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20161016_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
