# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20161016_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('remote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_service', models.CharField(blank=True, choices=[('Google', 'google')], max_length=100, null=True)),
                ('sync_token', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
    ]
