# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_remotecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecontact',
            name='etag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
