# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_remotecontact_etag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
