# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_auto_20161021_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotecontact',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Book'),
        ),
    ]
