# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-29 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_remotecontact_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
