# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-31 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_auto_20161229_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic_yearly', 'Basic Yearly Subscription'), ('basic_monthly', 'Basic Monthly Subscription'), ('family_yearly', 'Family Yearly Subscription'), ('team_monthly', 'Team Monthly Subscription'), ('team_yearly', 'Team Yearly Subscription'), ('family_monthly', 'Family Monthly Subscription')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic_yearly', 'Basic Yearly Subscription'), ('basic_monthly', 'Basic Monthly Subscription'), ('family_yearly', 'Family Yearly Subscription'), ('team_monthly', 'Team Monthly Subscription'), ('team_yearly', 'Team Yearly Subscription'), ('family_monthly', 'Family Monthly Subscription')], max_length=100),
        ),
    ]
