# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 04:17
from __future__ import unicode_literals

from django.db import migrations


def populate_bookowner_settings(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    BookOwner = apps.get_model("contacts", "BookOwner")
    profiles = Profile.objects.all()
    for profile in profiles:
        book_owners = BookOwner.objects.filter(user=profile.user)
        for book_owner in book_owners:
            book_owner.send_contact_reminders = profile.send_contact_reminders
            book_owner.send_birthday_reminders = profile.send_birthday_reminders
            book_owner.check_twitter_dms = profile.check_twitter_dms
            book_owner.check_twitter_mentions = profile.check_twitter_mentions
            book_owner.check_foursquare = profile.check_foursquare
            book_owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20170109_0401'),
        ('profiles', '0007_auto_20160905_1722'),
    ]

    operations = [
        migrations.RunPython(populate_bookowner_settings),
    ]
