# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-16 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_auto_20170221_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='bookowner',
            name='weekly_reminder_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
        ),
        migrations.AddField(
            model_name='historicalbookowner',
            name='weekly_reminder_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='plan',
            field=models.CharField(blank=True, choices=[('family_monthly', 'Family Monthly Subscription'), ('family_yearly', 'Family Yearly Subscription'), ('team_monthly', 'Team Monthly Subscription'), ('team_yearly', 'Team Yearly Subscription'), ('basic_yearly', 'Basic Yearly Subscription'), ('basic_monthly', 'Basic Monthly Subscription')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='plan',
            field=models.CharField(blank=True, choices=[('family_monthly', 'Family Monthly Subscription'), ('family_yearly', 'Family Yearly Subscription'), ('team_monthly', 'Team Monthly Subscription'), ('team_yearly', 'Team Yearly Subscription'), ('basic_yearly', 'Basic Yearly Subscription'), ('basic_monthly', 'Basic Monthly Subscription')], max_length=100),
        ),
    ]
