# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-22 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0036_auto_20170319_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbookowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
