# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='send_contact_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
