# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160427_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='check_twitter_dms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='check_twitter_mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='check_twitter_dms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='check_twitter_mentions',
            field=models.BooleanField(default=True),
        ),
    ]
