default_app_config = 'contacts.apps.ContactConfig'

FIELD_TYPE_EMAIL = 'email'
FIELD_TYPE_URL = 'url'
FIELD_TYPE_DATE = 'date'
FIELD_TYPE_TWITTER = 'twitter'
FIELD_TYPE_PHONE = 'phone'
FIELD_TYPE_ADDRESS = 'address'
FIELD_TYPE_TEXT = 'text'
FIELD_TYPE_BIG_TEXT = 'big_text'