# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_historicalbook_historicalbookowner_historicalcontact_historicallogentry_historicaltag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0003_auto_20150906_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvitation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('changed', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('error', 'error'), ('sent', 'sent'), ('accepted', 'accepted')], default='pending', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sent', models.DateTimeField(null=True)),
                ('key', models.CharField(db_index=True, max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.Book')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical invitation',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
    ]
